import Logo from './logo.svg'
import Play from './play.svg'
import Android from './android.svg'
import Web from './web.svg'
import Uiux from './uiux.svg'
import Mandiri from './mandiri.svg'
import Bukalapak from './Bukalapak.svg'
import Tokped from './Tokped.svg'
import Gojek from './Gojek.svg'
import Bca from './Bca.svg'
import Pertamina from './pertamina.svg'
import Bjb from './Bjb.svg'
import Cisco from './Cisco.svg'
import Workday from './Workday.svg'
import Ciputra from './ciputra.svg'
import Telkom from './telkom.svg'
import Trans from './Trans.svg'


export { Logo, Play, Android, Web, Uiux, Mandiri, Bukalapak, Tokped, Gojek, Bca, Pertamina, Bjb, Cisco, Workday, Ciputra, Telkom, Trans }